# Generated by Django 6.0.1 on 2026-01-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available_colors",
            field=models.ManyToManyField(blank=True, null=True, to="inventory.color"),
        ),
    ]
