# Generated by Django 6.0.1 on 2026-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_product_available_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flavour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="available_flavours",
            field=models.ManyToManyField(blank=True, null=True, to="inventory.flavour"),
        ),
    ]
