# Generated by Django 6.0.1 on 2026-02-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_flavour_product_available_flavours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
    ]
