# Generated by Django 6.0.1 on 2026-02-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_inquiry_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available_colors",
            field=models.ManyToManyField(blank=True, to="inventory.color"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_flavours",
            field=models.ManyToManyField(blank=True, to="inventory.flavour"),
        ),
    ]
